import type { NodeOfType, NodeType } from "./types";

/**
 * Node types grouped under a shared alias. Membership is by node `type`, and
 * each group backs an alias guard such as `is.Expression` or `is.Function`.
 */
export const ALIAS_GROUPS = {
  Expression: [
    "Identifier",
    "Literal",
    "ThisExpression",
    "Super",
    "ArrayExpression",
    "ObjectExpression",
    "FunctionExpression",
    "ArrowFunctionExpression",
    "ClassExpression",
    "TaggedTemplateExpression",
    "TemplateLiteral",
    "MemberExpression",
    "CallExpression",
    "NewExpression",
    "ChainExpression",
    "SequenceExpression",
    "ParenthesizedExpression",
    "BinaryExpression",
    "LogicalExpression",
    "ConditionalExpression",
    "UnaryExpression",
    "UpdateExpression",
    "AssignmentExpression",
    "YieldExpression",
    "AwaitExpression",
    "ImportExpression",
    "MetaProperty",
    "TSAsExpression",
    "TSSatisfiesExpression",
    "TSTypeAssertion",
    "TSNonNullExpression",
    "TSInstantiationExpression",
    "JSXElement",
    "JSXFragment",
  ],
  Statement: [
    "ExpressionStatement",
    "BlockStatement",
    "EmptyStatement",
    "DebuggerStatement",
    "ReturnStatement",
    "LabeledStatement",
    "BreakStatement",
    "ContinueStatement",
    "IfStatement",
    "SwitchStatement",
    "ThrowStatement",
    "TryStatement",
    "WhileStatement",
    "DoWhileStatement",
    "ForStatement",
    "ForInStatement",
    "ForOfStatement",
    "WithStatement",
    "FunctionDeclaration",
    "ClassDeclaration",
    "VariableDeclaration",
    "TSDeclareFunction",
    "TSTypeAliasDeclaration",
    "TSInterfaceDeclaration",
    "TSEnumDeclaration",
    "TSModuleDeclaration",
    "TSImportEqualsDeclaration",
  ],
  Declaration: [
    "FunctionDeclaration",
    "ClassDeclaration",
    "VariableDeclaration",
    "TSDeclareFunction",
    "TSTypeAliasDeclaration",
    "TSInterfaceDeclaration",
    "TSEnumDeclaration",
    "TSModuleDeclaration",
    "TSImportEqualsDeclaration",
  ],
  ModuleDeclaration: [
    "ImportDeclaration",
    "ExportNamedDeclaration",
    "ExportDefaultDeclaration",
    "ExportAllDeclaration",
    "TSExportAssignment",
    "TSNamespaceExportDeclaration",
  ],
  // Includes arrow functions, unlike the parser's narrower Function type.
  Function: [
    "FunctionDeclaration",
    "FunctionExpression",
    "ArrowFunctionExpression",
    "TSDeclareFunction",
    "TSEmptyBodyFunctionExpression",
  ],
  Class: ["ClassDeclaration", "ClassExpression"],
  Method: ["MethodDefinition", "TSAbstractMethodDefinition"],
  Loop: ["ForStatement", "ForInStatement", "ForOfStatement", "WhileStatement", "DoWhileStatement"],
  Pattern: ["Identifier", "ArrayPattern", "ObjectPattern", "AssignmentPattern", "RestElement"],
  JSX: [
    "JSXElement",
    "JSXOpeningElement",
    "JSXClosingElement",
    "JSXFragment",
    "JSXOpeningFragment",
    "JSXClosingFragment",
    "JSXIdentifier",
    "JSXNamespacedName",
    "JSXMemberExpression",
    "JSXAttribute",
    "JSXSpreadAttribute",
    "JSXExpressionContainer",
    "JSXEmptyExpression",
    "JSXText",
    "JSXSpreadChild",
  ],
  TSType: [
    "TSAnyKeyword",
    "TSUnknownKeyword",
    "TSNeverKeyword",
    "TSVoidKeyword",
    "TSNullKeyword",
    "TSUndefinedKeyword",
    "TSStringKeyword",
    "TSNumberKeyword",
    "TSBigIntKeyword",
    "TSBooleanKeyword",
    "TSSymbolKeyword",
    "TSObjectKeyword",
    "TSIntrinsicKeyword",
    "TSThisType",
    "TSTypeReference",
    "TSTypeQuery",
    "TSImportType",
    "TSLiteralType",
    "TSTemplateLiteralType",
    "TSArrayType",
    "TSIndexedAccessType",
    "TSTupleType",
    "TSNamedTupleMember",
    "TSJSDocNullableType",
    "TSJSDocNonNullableType",
    "TSJSDocUnknownType",
    "TSUnionType",
    "TSIntersectionType",
    "TSConditionalType",
    "TSInferType",
    "TSTypeOperator",
    "TSParenthesizedType",
    "TSFunctionType",
    "TSConstructorType",
    "TSTypePredicate",
    "TSTypeLiteral",
    "TSMappedType",
  ],
} as const satisfies Record<string, readonly NodeType[]>;

/** Name of an alias group. */
export type AliasName = keyof typeof ALIAS_GROUPS;

/** Node union matched by each alias group. */
export type AliasMap = {
  [K in AliasName]: NodeOfType<(typeof ALIAS_GROUPS)[K][number]>;
};
